export { default as Home } from './home';
export * from './login';
export * from './register';
export * from './forgotPassword';
export * from './company-list/list';
export * from './company-list/create';
// export { default as Dashboard } from './Dashboard';
// export { default as ResetPassword } from './ResetPassword';
// export { default as NotFound } from './NotFound';
// export { default as ServerError } from './ServerError';
